name = "LookupTable"
uuid = "b19a02b0-50d5-4973-af73-300db3db3939"
authors = ["Hiroyuki Okamura <okamu@hiroshima-u.ac.jp> and contributors"]
version = "0.9.0"

[deps]

[compat]
julia = "1.8"

[extras]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "CSV", "DataFrames"]
