name = "LookupTable"
uuid = "b19a02b0-50d5-4973-af73-300db3db3939"
authors = ["Hiroyuki Okamura <okamu@hiroshima-u.ac.jp> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
